### ISSUE TITLE
Is it possible to put in more items ?

### ISSUE THREAD

**Issue by pgjgj** [Dajmanek/VillagerShop#1]
Hello i have a little question. I wanted to know if it was simple to add a bigger gui for item adding.  
![image](https://user-images.githubusercontent.com/8484834/147590964-fa981d53-1f11-4ab2-b3b2-7c8418dacf29.png)
i want to make a shop this big but can't actually.

**Comment by Dajmanek** [comment]
Hi, at the moment it is not possible to add more than 18 offers.
I will try to develop such an option, but I do not have much time now, so the update may not appear until some time (2-3 weeks).
Until then, you can, for example, create two similar categories - blocks, blocks 2.

By the way, I don't understand this image, the way of creating a store is different from the image. What did you want to show with it?

**Comment by pgjgj** [comment]
Okay no problem. I was trying to show the number of exchanges i was trying to make that's why it doesn't looks like the gui. 

Happy new year to you !

**Comment by Dajmanek** [comment]
I'm not sure if I understood the picture correctly, but I think you want to do exactly 18 exchange offers.
If so, you can arrange them in a gui like this:

![Zrzut ekranu 2022-01-01 193041](https://user-images.githubusercontent.com/72786608/147857706-4fb9a084-3a55-4025-8116-e0af6434bf73.png)

And happy new your to you too :D

**Comment by pgjgj** [comment]
Actually the charcoal and the coal are supposed to have one case for each so it goes to a 19 items shop. So I've just removed the charcoal

**Comment by Dajmanek** [comment]
Ah okay it makes sense now.
So like i said for some time probably will be the sollution of this issue.

**Comment by Dajmanek** [comment]
Added ability to create more than 18 offers in update 1.5. :)
